-- Gerado automaticamente por scripts/generate-seed.mjs
-- Total: 995 figurinhas (FCW 0-20, 48 países × 1-20, Coca-Cola 1-14)

insert into stickers (section_type, section, number) values
  ('fcw', 'FWC', 0),
  ('fcw', 'FWC', 1),
  ('fcw', 'FWC', 2),
  ('fcw', 'FWC', 3),
  ('fcw', 'FWC', 4),
  ('fcw', 'FWC', 5),
  ('fcw', 'FWC', 6),
  ('fcw', 'FWC', 7),
  ('fcw', 'FWC', 8),
  ('fcw', 'FWC', 9),
  ('fcw', 'FWC', 10),
  ('fcw', 'FWC', 11),
  ('fcw', 'FWC', 12),
  ('fcw', 'FWC', 13),
  ('fcw', 'FWC', 14),
  ('fcw', 'FWC', 15),
  ('fcw', 'FWC', 16),
  ('fcw', 'FWC', 17),
  ('fcw', 'FWC', 18),
  ('fcw', 'FWC', 19),
  ('fcw', 'FWC', 20),
  ('pais', 'México', 1),
  ('pais', 'México', 2),
  ('pais', 'México', 3),
  ('pais', 'México', 4),
  ('pais', 'México', 5),
  ('pais', 'México', 6),
  ('pais', 'México', 7),
  ('pais', 'México', 8),
  ('pais', 'México', 9),
  ('pais', 'México', 10),
  ('pais', 'México', 11),
  ('pais', 'México', 12),
  ('pais', 'México', 13),
  ('pais', 'México', 14),
  ('pais', 'México', 15),
  ('pais', 'México', 16),
  ('pais', 'México', 17),
  ('pais', 'México', 18),
  ('pais', 'México', 19),
  ('pais', 'México', 20),
  ('pais', 'África do Sul', 1),
  ('pais', 'África do Sul', 2),
  ('pais', 'África do Sul', 3),
  ('pais', 'África do Sul', 4),
  ('pais', 'África do Sul', 5),
  ('pais', 'África do Sul', 6),
  ('pais', 'África do Sul', 7),
  ('pais', 'África do Sul', 8),
  ('pais', 'África do Sul', 9),
  ('pais', 'África do Sul', 10),
  ('pais', 'África do Sul', 11),
  ('pais', 'África do Sul', 12),
  ('pais', 'África do Sul', 13),
  ('pais', 'África do Sul', 14),
  ('pais', 'África do Sul', 15),
  ('pais', 'África do Sul', 16),
  ('pais', 'África do Sul', 17),
  ('pais', 'África do Sul', 18),
  ('pais', 'África do Sul', 19),
  ('pais', 'África do Sul', 20),
  ('pais', 'Coreia do Sul', 1),
  ('pais', 'Coreia do Sul', 2),
  ('pais', 'Coreia do Sul', 3),
  ('pais', 'Coreia do Sul', 4),
  ('pais', 'Coreia do Sul', 5),
  ('pais', 'Coreia do Sul', 6),
  ('pais', 'Coreia do Sul', 7),
  ('pais', 'Coreia do Sul', 8),
  ('pais', 'Coreia do Sul', 9),
  ('pais', 'Coreia do Sul', 10),
  ('pais', 'Coreia do Sul', 11),
  ('pais', 'Coreia do Sul', 12),
  ('pais', 'Coreia do Sul', 13),
  ('pais', 'Coreia do Sul', 14),
  ('pais', 'Coreia do Sul', 15),
  ('pais', 'Coreia do Sul', 16),
  ('pais', 'Coreia do Sul', 17),
  ('pais', 'Coreia do Sul', 18),
  ('pais', 'Coreia do Sul', 19),
  ('pais', 'Coreia do Sul', 20),
  ('pais', 'Dinamarca', 1),
  ('pais', 'Dinamarca', 2),
  ('pais', 'Dinamarca', 3),
  ('pais', 'Dinamarca', 4),
  ('pais', 'Dinamarca', 5),
  ('pais', 'Dinamarca', 6),
  ('pais', 'Dinamarca', 7),
  ('pais', 'Dinamarca', 8),
  ('pais', 'Dinamarca', 9),
  ('pais', 'Dinamarca', 10),
  ('pais', 'Dinamarca', 11),
  ('pais', 'Dinamarca', 12),
  ('pais', 'Dinamarca', 13),
  ('pais', 'Dinamarca', 14),
  ('pais', 'Dinamarca', 15),
  ('pais', 'Dinamarca', 16),
  ('pais', 'Dinamarca', 17),
  ('pais', 'Dinamarca', 18),
  ('pais', 'Dinamarca', 19),
  ('pais', 'Dinamarca', 20),
  ('pais', 'Canadá', 1),
  ('pais', 'Canadá', 2),
  ('pais', 'Canadá', 3),
  ('pais', 'Canadá', 4),
  ('pais', 'Canadá', 5),
  ('pais', 'Canadá', 6),
  ('pais', 'Canadá', 7),
  ('pais', 'Canadá', 8),
  ('pais', 'Canadá', 9),
  ('pais', 'Canadá', 10),
  ('pais', 'Canadá', 11),
  ('pais', 'Canadá', 12),
  ('pais', 'Canadá', 13),
  ('pais', 'Canadá', 14),
  ('pais', 'Canadá', 15),
  ('pais', 'Canadá', 16),
  ('pais', 'Canadá', 17),
  ('pais', 'Canadá', 18),
  ('pais', 'Canadá', 19),
  ('pais', 'Canadá', 20),
  ('pais', 'Catar', 1),
  ('pais', 'Catar', 2),
  ('pais', 'Catar', 3),
  ('pais', 'Catar', 4),
  ('pais', 'Catar', 5),
  ('pais', 'Catar', 6),
  ('pais', 'Catar', 7),
  ('pais', 'Catar', 8),
  ('pais', 'Catar', 9),
  ('pais', 'Catar', 10),
  ('pais', 'Catar', 11),
  ('pais', 'Catar', 12),
  ('pais', 'Catar', 13),
  ('pais', 'Catar', 14),
  ('pais', 'Catar', 15),
  ('pais', 'Catar', 16),
  ('pais', 'Catar', 17),
  ('pais', 'Catar', 18),
  ('pais', 'Catar', 19),
  ('pais', 'Catar', 20),
  ('pais', 'Suíça', 1),
  ('pais', 'Suíça', 2),
  ('pais', 'Suíça', 3),
  ('pais', 'Suíça', 4),
  ('pais', 'Suíça', 5),
  ('pais', 'Suíça', 6),
  ('pais', 'Suíça', 7),
  ('pais', 'Suíça', 8),
  ('pais', 'Suíça', 9),
  ('pais', 'Suíça', 10),
  ('pais', 'Suíça', 11),
  ('pais', 'Suíça', 12),
  ('pais', 'Suíça', 13),
  ('pais', 'Suíça', 14),
  ('pais', 'Suíça', 15),
  ('pais', 'Suíça', 16),
  ('pais', 'Suíça', 17),
  ('pais', 'Suíça', 18),
  ('pais', 'Suíça', 19),
  ('pais', 'Suíça', 20),
  ('pais', 'Itália', 1),
  ('pais', 'Itália', 2),
  ('pais', 'Itália', 3),
  ('pais', 'Itália', 4),
  ('pais', 'Itália', 5),
  ('pais', 'Itália', 6),
  ('pais', 'Itália', 7),
  ('pais', 'Itália', 8),
  ('pais', 'Itália', 9),
  ('pais', 'Itália', 10),
  ('pais', 'Itália', 11),
  ('pais', 'Itália', 12),
  ('pais', 'Itália', 13),
  ('pais', 'Itália', 14),
  ('pais', 'Itália', 15),
  ('pais', 'Itália', 16),
  ('pais', 'Itália', 17),
  ('pais', 'Itália', 18),
  ('pais', 'Itália', 19),
  ('pais', 'Itália', 20),
  ('pais', 'Brasil', 1),
  ('pais', 'Brasil', 2),
  ('pais', 'Brasil', 3),
  ('pais', 'Brasil', 4),
  ('pais', 'Brasil', 5),
  ('pais', 'Brasil', 6),
  ('pais', 'Brasil', 7),
  ('pais', 'Brasil', 8),
  ('pais', 'Brasil', 9),
  ('pais', 'Brasil', 10),
  ('pais', 'Brasil', 11),
  ('pais', 'Brasil', 12),
  ('pais', 'Brasil', 13),
  ('pais', 'Brasil', 14),
  ('pais', 'Brasil', 15),
  ('pais', 'Brasil', 16),
  ('pais', 'Brasil', 17),
  ('pais', 'Brasil', 18),
  ('pais', 'Brasil', 19),
  ('pais', 'Brasil', 20),
  ('pais', 'Marrocos', 1),
  ('pais', 'Marrocos', 2),
  ('pais', 'Marrocos', 3),
  ('pais', 'Marrocos', 4),
  ('pais', 'Marrocos', 5),
  ('pais', 'Marrocos', 6),
  ('pais', 'Marrocos', 7),
  ('pais', 'Marrocos', 8),
  ('pais', 'Marrocos', 9),
  ('pais', 'Marrocos', 10),
  ('pais', 'Marrocos', 11),
  ('pais', 'Marrocos', 12),
  ('pais', 'Marrocos', 13),
  ('pais', 'Marrocos', 14),
  ('pais', 'Marrocos', 15),
  ('pais', 'Marrocos', 16),
  ('pais', 'Marrocos', 17),
  ('pais', 'Marrocos', 18),
  ('pais', 'Marrocos', 19),
  ('pais', 'Marrocos', 20),
  ('pais', 'Haiti', 1),
  ('pais', 'Haiti', 2),
  ('pais', 'Haiti', 3),
  ('pais', 'Haiti', 4),
  ('pais', 'Haiti', 5),
  ('pais', 'Haiti', 6),
  ('pais', 'Haiti', 7),
  ('pais', 'Haiti', 8),
  ('pais', 'Haiti', 9),
  ('pais', 'Haiti', 10),
  ('pais', 'Haiti', 11),
  ('pais', 'Haiti', 12),
  ('pais', 'Haiti', 13),
  ('pais', 'Haiti', 14),
  ('pais', 'Haiti', 15),
  ('pais', 'Haiti', 16),
  ('pais', 'Haiti', 17),
  ('pais', 'Haiti', 18),
  ('pais', 'Haiti', 19),
  ('pais', 'Haiti', 20),
  ('pais', 'Escócia', 1),
  ('pais', 'Escócia', 2),
  ('pais', 'Escócia', 3),
  ('pais', 'Escócia', 4),
  ('pais', 'Escócia', 5),
  ('pais', 'Escócia', 6),
  ('pais', 'Escócia', 7),
  ('pais', 'Escócia', 8),
  ('pais', 'Escócia', 9),
  ('pais', 'Escócia', 10),
  ('pais', 'Escócia', 11),
  ('pais', 'Escócia', 12),
  ('pais', 'Escócia', 13),
  ('pais', 'Escócia', 14),
  ('pais', 'Escócia', 15),
  ('pais', 'Escócia', 16),
  ('pais', 'Escócia', 17),
  ('pais', 'Escócia', 18),
  ('pais', 'Escócia', 19),
  ('pais', 'Escócia', 20),
  ('pais', 'Estados Unidos', 1),
  ('pais', 'Estados Unidos', 2),
  ('pais', 'Estados Unidos', 3),
  ('pais', 'Estados Unidos', 4),
  ('pais', 'Estados Unidos', 5),
  ('pais', 'Estados Unidos', 6),
  ('pais', 'Estados Unidos', 7),
  ('pais', 'Estados Unidos', 8),
  ('pais', 'Estados Unidos', 9),
  ('pais', 'Estados Unidos', 10),
  ('pais', 'Estados Unidos', 11),
  ('pais', 'Estados Unidos', 12),
  ('pais', 'Estados Unidos', 13),
  ('pais', 'Estados Unidos', 14),
  ('pais', 'Estados Unidos', 15),
  ('pais', 'Estados Unidos', 16),
  ('pais', 'Estados Unidos', 17),
  ('pais', 'Estados Unidos', 18),
  ('pais', 'Estados Unidos', 19),
  ('pais', 'Estados Unidos', 20),
  ('pais', 'Paraguai', 1),
  ('pais', 'Paraguai', 2),
  ('pais', 'Paraguai', 3),
  ('pais', 'Paraguai', 4),
  ('pais', 'Paraguai', 5),
  ('pais', 'Paraguai', 6),
  ('pais', 'Paraguai', 7),
  ('pais', 'Paraguai', 8),
  ('pais', 'Paraguai', 9),
  ('pais', 'Paraguai', 10),
  ('pais', 'Paraguai', 11),
  ('pais', 'Paraguai', 12),
  ('pais', 'Paraguai', 13),
  ('pais', 'Paraguai', 14),
  ('pais', 'Paraguai', 15),
  ('pais', 'Paraguai', 16),
  ('pais', 'Paraguai', 17),
  ('pais', 'Paraguai', 18),
  ('pais', 'Paraguai', 19),
  ('pais', 'Paraguai', 20),
  ('pais', 'Austrália', 1),
  ('pais', 'Austrália', 2),
  ('pais', 'Austrália', 3),
  ('pais', 'Austrália', 4),
  ('pais', 'Austrália', 5),
  ('pais', 'Austrália', 6),
  ('pais', 'Austrália', 7),
  ('pais', 'Austrália', 8),
  ('pais', 'Austrália', 9),
  ('pais', 'Austrália', 10),
  ('pais', 'Austrália', 11),
  ('pais', 'Austrália', 12),
  ('pais', 'Austrália', 13),
  ('pais', 'Austrália', 14),
  ('pais', 'Austrália', 15),
  ('pais', 'Austrália', 16),
  ('pais', 'Austrália', 17),
  ('pais', 'Austrália', 18),
  ('pais', 'Austrália', 19),
  ('pais', 'Austrália', 20),
  ('pais', 'Turquia', 1),
  ('pais', 'Turquia', 2),
  ('pais', 'Turquia', 3),
  ('pais', 'Turquia', 4),
  ('pais', 'Turquia', 5),
  ('pais', 'Turquia', 6),
  ('pais', 'Turquia', 7),
  ('pais', 'Turquia', 8),
  ('pais', 'Turquia', 9),
  ('pais', 'Turquia', 10),
  ('pais', 'Turquia', 11),
  ('pais', 'Turquia', 12),
  ('pais', 'Turquia', 13),
  ('pais', 'Turquia', 14),
  ('pais', 'Turquia', 15),
  ('pais', 'Turquia', 16),
  ('pais', 'Turquia', 17),
  ('pais', 'Turquia', 18),
  ('pais', 'Turquia', 19),
  ('pais', 'Turquia', 20),
  ('pais', 'Alemanha', 1),
  ('pais', 'Alemanha', 2),
  ('pais', 'Alemanha', 3),
  ('pais', 'Alemanha', 4),
  ('pais', 'Alemanha', 5),
  ('pais', 'Alemanha', 6),
  ('pais', 'Alemanha', 7),
  ('pais', 'Alemanha', 8),
  ('pais', 'Alemanha', 9),
  ('pais', 'Alemanha', 10),
  ('pais', 'Alemanha', 11),
  ('pais', 'Alemanha', 12),
  ('pais', 'Alemanha', 13),
  ('pais', 'Alemanha', 14),
  ('pais', 'Alemanha', 15),
  ('pais', 'Alemanha', 16),
  ('pais', 'Alemanha', 17),
  ('pais', 'Alemanha', 18),
  ('pais', 'Alemanha', 19),
  ('pais', 'Alemanha', 20),
  ('pais', 'Curaçao', 1),
  ('pais', 'Curaçao', 2),
  ('pais', 'Curaçao', 3),
  ('pais', 'Curaçao', 4),
  ('pais', 'Curaçao', 5),
  ('pais', 'Curaçao', 6),
  ('pais', 'Curaçao', 7),
  ('pais', 'Curaçao', 8),
  ('pais', 'Curaçao', 9),
  ('pais', 'Curaçao', 10),
  ('pais', 'Curaçao', 11),
  ('pais', 'Curaçao', 12),
  ('pais', 'Curaçao', 13),
  ('pais', 'Curaçao', 14),
  ('pais', 'Curaçao', 15),
  ('pais', 'Curaçao', 16),
  ('pais', 'Curaçao', 17),
  ('pais', 'Curaçao', 18),
  ('pais', 'Curaçao', 19),
  ('pais', 'Curaçao', 20),
  ('pais', 'Costa do Marfim', 1),
  ('pais', 'Costa do Marfim', 2),
  ('pais', 'Costa do Marfim', 3),
  ('pais', 'Costa do Marfim', 4),
  ('pais', 'Costa do Marfim', 5),
  ('pais', 'Costa do Marfim', 6),
  ('pais', 'Costa do Marfim', 7),
  ('pais', 'Costa do Marfim', 8),
  ('pais', 'Costa do Marfim', 9),
  ('pais', 'Costa do Marfim', 10),
  ('pais', 'Costa do Marfim', 11),
  ('pais', 'Costa do Marfim', 12),
  ('pais', 'Costa do Marfim', 13),
  ('pais', 'Costa do Marfim', 14),
  ('pais', 'Costa do Marfim', 15),
  ('pais', 'Costa do Marfim', 16),
  ('pais', 'Costa do Marfim', 17),
  ('pais', 'Costa do Marfim', 18),
  ('pais', 'Costa do Marfim', 19),
  ('pais', 'Costa do Marfim', 20),
  ('pais', 'Equador', 1),
  ('pais', 'Equador', 2),
  ('pais', 'Equador', 3),
  ('pais', 'Equador', 4),
  ('pais', 'Equador', 5),
  ('pais', 'Equador', 6),
  ('pais', 'Equador', 7),
  ('pais', 'Equador', 8),
  ('pais', 'Equador', 9),
  ('pais', 'Equador', 10),
  ('pais', 'Equador', 11),
  ('pais', 'Equador', 12),
  ('pais', 'Equador', 13),
  ('pais', 'Equador', 14),
  ('pais', 'Equador', 15),
  ('pais', 'Equador', 16),
  ('pais', 'Equador', 17),
  ('pais', 'Equador', 18),
  ('pais', 'Equador', 19),
  ('pais', 'Equador', 20),
  ('pais', 'Países Baixos', 1),
  ('pais', 'Países Baixos', 2),
  ('pais', 'Países Baixos', 3),
  ('pais', 'Países Baixos', 4),
  ('pais', 'Países Baixos', 5),
  ('pais', 'Países Baixos', 6),
  ('pais', 'Países Baixos', 7),
  ('pais', 'Países Baixos', 8),
  ('pais', 'Países Baixos', 9),
  ('pais', 'Países Baixos', 10),
  ('pais', 'Países Baixos', 11),
  ('pais', 'Países Baixos', 12),
  ('pais', 'Países Baixos', 13),
  ('pais', 'Países Baixos', 14),
  ('pais', 'Países Baixos', 15),
  ('pais', 'Países Baixos', 16),
  ('pais', 'Países Baixos', 17),
  ('pais', 'Países Baixos', 18),
  ('pais', 'Países Baixos', 19),
  ('pais', 'Países Baixos', 20),
  ('pais', 'Japão', 1),
  ('pais', 'Japão', 2),
  ('pais', 'Japão', 3),
  ('pais', 'Japão', 4),
  ('pais', 'Japão', 5),
  ('pais', 'Japão', 6),
  ('pais', 'Japão', 7),
  ('pais', 'Japão', 8),
  ('pais', 'Japão', 9),
  ('pais', 'Japão', 10),
  ('pais', 'Japão', 11),
  ('pais', 'Japão', 12),
  ('pais', 'Japão', 13),
  ('pais', 'Japão', 14),
  ('pais', 'Japão', 15),
  ('pais', 'Japão', 16),
  ('pais', 'Japão', 17),
  ('pais', 'Japão', 18),
  ('pais', 'Japão', 19),
  ('pais', 'Japão', 20),
  ('pais', 'Tunísia', 1),
  ('pais', 'Tunísia', 2),
  ('pais', 'Tunísia', 3),
  ('pais', 'Tunísia', 4),
  ('pais', 'Tunísia', 5),
  ('pais', 'Tunísia', 6),
  ('pais', 'Tunísia', 7),
  ('pais', 'Tunísia', 8),
  ('pais', 'Tunísia', 9),
  ('pais', 'Tunísia', 10),
  ('pais', 'Tunísia', 11),
  ('pais', 'Tunísia', 12),
  ('pais', 'Tunísia', 13),
  ('pais', 'Tunísia', 14),
  ('pais', 'Tunísia', 15),
  ('pais', 'Tunísia', 16),
  ('pais', 'Tunísia', 17),
  ('pais', 'Tunísia', 18),
  ('pais', 'Tunísia', 19),
  ('pais', 'Tunísia', 20),
  ('pais', 'Rep. Tcheca', 1),
  ('pais', 'Rep. Tcheca', 2),
  ('pais', 'Rep. Tcheca', 3),
  ('pais', 'Rep. Tcheca', 4),
  ('pais', 'Rep. Tcheca', 5),
  ('pais', 'Rep. Tcheca', 6),
  ('pais', 'Rep. Tcheca', 7),
  ('pais', 'Rep. Tcheca', 8),
  ('pais', 'Rep. Tcheca', 9),
  ('pais', 'Rep. Tcheca', 10),
  ('pais', 'Rep. Tcheca', 11),
  ('pais', 'Rep. Tcheca', 12),
  ('pais', 'Rep. Tcheca', 13),
  ('pais', 'Rep. Tcheca', 14),
  ('pais', 'Rep. Tcheca', 15),
  ('pais', 'Rep. Tcheca', 16),
  ('pais', 'Rep. Tcheca', 17),
  ('pais', 'Rep. Tcheca', 18),
  ('pais', 'Rep. Tcheca', 19),
  ('pais', 'Rep. Tcheca', 20),
  ('pais', 'Bélgica', 1),
  ('pais', 'Bélgica', 2),
  ('pais', 'Bélgica', 3),
  ('pais', 'Bélgica', 4),
  ('pais', 'Bélgica', 5),
  ('pais', 'Bélgica', 6),
  ('pais', 'Bélgica', 7),
  ('pais', 'Bélgica', 8),
  ('pais', 'Bélgica', 9),
  ('pais', 'Bélgica', 10),
  ('pais', 'Bélgica', 11),
  ('pais', 'Bélgica', 12),
  ('pais', 'Bélgica', 13),
  ('pais', 'Bélgica', 14),
  ('pais', 'Bélgica', 15),
  ('pais', 'Bélgica', 16),
  ('pais', 'Bélgica', 17),
  ('pais', 'Bélgica', 18),
  ('pais', 'Bélgica', 19),
  ('pais', 'Bélgica', 20),
  ('pais', 'Egito', 1),
  ('pais', 'Egito', 2),
  ('pais', 'Egito', 3),
  ('pais', 'Egito', 4),
  ('pais', 'Egito', 5),
  ('pais', 'Egito', 6),
  ('pais', 'Egito', 7),
  ('pais', 'Egito', 8),
  ('pais', 'Egito', 9),
  ('pais', 'Egito', 10),
  ('pais', 'Egito', 11),
  ('pais', 'Egito', 12),
  ('pais', 'Egito', 13),
  ('pais', 'Egito', 14),
  ('pais', 'Egito', 15),
  ('pais', 'Egito', 16),
  ('pais', 'Egito', 17),
  ('pais', 'Egito', 18),
  ('pais', 'Egito', 19),
  ('pais', 'Egito', 20),
  ('pais', 'Irã', 1),
  ('pais', 'Irã', 2),
  ('pais', 'Irã', 3),
  ('pais', 'Irã', 4),
  ('pais', 'Irã', 5),
  ('pais', 'Irã', 6),
  ('pais', 'Irã', 7),
  ('pais', 'Irã', 8),
  ('pais', 'Irã', 9),
  ('pais', 'Irã', 10),
  ('pais', 'Irã', 11),
  ('pais', 'Irã', 12),
  ('pais', 'Irã', 13),
  ('pais', 'Irã', 14),
  ('pais', 'Irã', 15),
  ('pais', 'Irã', 16),
  ('pais', 'Irã', 17),
  ('pais', 'Irã', 18),
  ('pais', 'Irã', 19),
  ('pais', 'Irã', 20),
  ('pais', 'Nova Zelândia', 1),
  ('pais', 'Nova Zelândia', 2),
  ('pais', 'Nova Zelândia', 3),
  ('pais', 'Nova Zelândia', 4),
  ('pais', 'Nova Zelândia', 5),
  ('pais', 'Nova Zelândia', 6),
  ('pais', 'Nova Zelândia', 7),
  ('pais', 'Nova Zelândia', 8),
  ('pais', 'Nova Zelândia', 9),
  ('pais', 'Nova Zelândia', 10),
  ('pais', 'Nova Zelândia', 11),
  ('pais', 'Nova Zelândia', 12),
  ('pais', 'Nova Zelândia', 13),
  ('pais', 'Nova Zelândia', 14),
  ('pais', 'Nova Zelândia', 15),
  ('pais', 'Nova Zelândia', 16),
  ('pais', 'Nova Zelândia', 17),
  ('pais', 'Nova Zelândia', 18),
  ('pais', 'Nova Zelândia', 19),
  ('pais', 'Nova Zelândia', 20),
  ('pais', 'Espanha', 1),
  ('pais', 'Espanha', 2),
  ('pais', 'Espanha', 3),
  ('pais', 'Espanha', 4),
  ('pais', 'Espanha', 5),
  ('pais', 'Espanha', 6),
  ('pais', 'Espanha', 7),
  ('pais', 'Espanha', 8),
  ('pais', 'Espanha', 9),
  ('pais', 'Espanha', 10),
  ('pais', 'Espanha', 11),
  ('pais', 'Espanha', 12),
  ('pais', 'Espanha', 13),
  ('pais', 'Espanha', 14),
  ('pais', 'Espanha', 15),
  ('pais', 'Espanha', 16),
  ('pais', 'Espanha', 17),
  ('pais', 'Espanha', 18),
  ('pais', 'Espanha', 19),
  ('pais', 'Espanha', 20),
  ('pais', 'Cabo Verde', 1),
  ('pais', 'Cabo Verde', 2),
  ('pais', 'Cabo Verde', 3),
  ('pais', 'Cabo Verde', 4),
  ('pais', 'Cabo Verde', 5),
  ('pais', 'Cabo Verde', 6),
  ('pais', 'Cabo Verde', 7),
  ('pais', 'Cabo Verde', 8),
  ('pais', 'Cabo Verde', 9),
  ('pais', 'Cabo Verde', 10),
  ('pais', 'Cabo Verde', 11),
  ('pais', 'Cabo Verde', 12),
  ('pais', 'Cabo Verde', 13),
  ('pais', 'Cabo Verde', 14),
  ('pais', 'Cabo Verde', 15),
  ('pais', 'Cabo Verde', 16),
  ('pais', 'Cabo Verde', 17),
  ('pais', 'Cabo Verde', 18),
  ('pais', 'Cabo Verde', 19),
  ('pais', 'Cabo Verde', 20),
  ('pais', 'Arábia Saudita', 1),
  ('pais', 'Arábia Saudita', 2),
  ('pais', 'Arábia Saudita', 3),
  ('pais', 'Arábia Saudita', 4),
  ('pais', 'Arábia Saudita', 5),
  ('pais', 'Arábia Saudita', 6),
  ('pais', 'Arábia Saudita', 7),
  ('pais', 'Arábia Saudita', 8),
  ('pais', 'Arábia Saudita', 9),
  ('pais', 'Arábia Saudita', 10),
  ('pais', 'Arábia Saudita', 11),
  ('pais', 'Arábia Saudita', 12),
  ('pais', 'Arábia Saudita', 13),
  ('pais', 'Arábia Saudita', 14),
  ('pais', 'Arábia Saudita', 15),
  ('pais', 'Arábia Saudita', 16),
  ('pais', 'Arábia Saudita', 17),
  ('pais', 'Arábia Saudita', 18),
  ('pais', 'Arábia Saudita', 19),
  ('pais', 'Arábia Saudita', 20),
  ('pais', 'Uruguai', 1),
  ('pais', 'Uruguai', 2),
  ('pais', 'Uruguai', 3),
  ('pais', 'Uruguai', 4),
  ('pais', 'Uruguai', 5),
  ('pais', 'Uruguai', 6),
  ('pais', 'Uruguai', 7),
  ('pais', 'Uruguai', 8),
  ('pais', 'Uruguai', 9),
  ('pais', 'Uruguai', 10),
  ('pais', 'Uruguai', 11),
  ('pais', 'Uruguai', 12),
  ('pais', 'Uruguai', 13),
  ('pais', 'Uruguai', 14),
  ('pais', 'Uruguai', 15),
  ('pais', 'Uruguai', 16),
  ('pais', 'Uruguai', 17),
  ('pais', 'Uruguai', 18),
  ('pais', 'Uruguai', 19),
  ('pais', 'Uruguai', 20),
  ('pais', 'França', 1),
  ('pais', 'França', 2),
  ('pais', 'França', 3),
  ('pais', 'França', 4),
  ('pais', 'França', 5),
  ('pais', 'França', 6),
  ('pais', 'França', 7),
  ('pais', 'França', 8),
  ('pais', 'França', 9),
  ('pais', 'França', 10),
  ('pais', 'França', 11),
  ('pais', 'França', 12),
  ('pais', 'França', 13),
  ('pais', 'França', 14),
  ('pais', 'França', 15),
  ('pais', 'França', 16),
  ('pais', 'França', 17),
  ('pais', 'França', 18),
  ('pais', 'França', 19),
  ('pais', 'França', 20),
  ('pais', 'Senegal', 1),
  ('pais', 'Senegal', 2),
  ('pais', 'Senegal', 3),
  ('pais', 'Senegal', 4),
  ('pais', 'Senegal', 5),
  ('pais', 'Senegal', 6),
  ('pais', 'Senegal', 7),
  ('pais', 'Senegal', 8),
  ('pais', 'Senegal', 9),
  ('pais', 'Senegal', 10),
  ('pais', 'Senegal', 11),
  ('pais', 'Senegal', 12),
  ('pais', 'Senegal', 13),
  ('pais', 'Senegal', 14),
  ('pais', 'Senegal', 15),
  ('pais', 'Senegal', 16),
  ('pais', 'Senegal', 17),
  ('pais', 'Senegal', 18),
  ('pais', 'Senegal', 19),
  ('pais', 'Senegal', 20),
  ('pais', 'Noruega', 1),
  ('pais', 'Noruega', 2),
  ('pais', 'Noruega', 3),
  ('pais', 'Noruega', 4),
  ('pais', 'Noruega', 5),
  ('pais', 'Noruega', 6),
  ('pais', 'Noruega', 7),
  ('pais', 'Noruega', 8),
  ('pais', 'Noruega', 9),
  ('pais', 'Noruega', 10),
  ('pais', 'Noruega', 11),
  ('pais', 'Noruega', 12),
  ('pais', 'Noruega', 13),
  ('pais', 'Noruega', 14),
  ('pais', 'Noruega', 15),
  ('pais', 'Noruega', 16),
  ('pais', 'Noruega', 17),
  ('pais', 'Noruega', 18),
  ('pais', 'Noruega', 19),
  ('pais', 'Noruega', 20),
  ('pais', 'Irlanda', 1),
  ('pais', 'Irlanda', 2),
  ('pais', 'Irlanda', 3),
  ('pais', 'Irlanda', 4),
  ('pais', 'Irlanda', 5),
  ('pais', 'Irlanda', 6),
  ('pais', 'Irlanda', 7),
  ('pais', 'Irlanda', 8),
  ('pais', 'Irlanda', 9),
  ('pais', 'Irlanda', 10),
  ('pais', 'Irlanda', 11),
  ('pais', 'Irlanda', 12),
  ('pais', 'Irlanda', 13),
  ('pais', 'Irlanda', 14),
  ('pais', 'Irlanda', 15),
  ('pais', 'Irlanda', 16),
  ('pais', 'Irlanda', 17),
  ('pais', 'Irlanda', 18),
  ('pais', 'Irlanda', 19),
  ('pais', 'Irlanda', 20),
  ('pais', 'Argentina', 1),
  ('pais', 'Argentina', 2),
  ('pais', 'Argentina', 3),
  ('pais', 'Argentina', 4),
  ('pais', 'Argentina', 5),
  ('pais', 'Argentina', 6),
  ('pais', 'Argentina', 7),
  ('pais', 'Argentina', 8),
  ('pais', 'Argentina', 9),
  ('pais', 'Argentina', 10),
  ('pais', 'Argentina', 11),
  ('pais', 'Argentina', 12),
  ('pais', 'Argentina', 13),
  ('pais', 'Argentina', 14),
  ('pais', 'Argentina', 15),
  ('pais', 'Argentina', 16),
  ('pais', 'Argentina', 17),
  ('pais', 'Argentina', 18),
  ('pais', 'Argentina', 19),
  ('pais', 'Argentina', 20),
  ('pais', 'Argélia', 1),
  ('pais', 'Argélia', 2),
  ('pais', 'Argélia', 3),
  ('pais', 'Argélia', 4),
  ('pais', 'Argélia', 5),
  ('pais', 'Argélia', 6),
  ('pais', 'Argélia', 7),
  ('pais', 'Argélia', 8),
  ('pais', 'Argélia', 9),
  ('pais', 'Argélia', 10),
  ('pais', 'Argélia', 11),
  ('pais', 'Argélia', 12),
  ('pais', 'Argélia', 13),
  ('pais', 'Argélia', 14),
  ('pais', 'Argélia', 15),
  ('pais', 'Argélia', 16),
  ('pais', 'Argélia', 17),
  ('pais', 'Argélia', 18),
  ('pais', 'Argélia', 19),
  ('pais', 'Argélia', 20),
  ('pais', 'Áustria', 1),
  ('pais', 'Áustria', 2),
  ('pais', 'Áustria', 3),
  ('pais', 'Áustria', 4),
  ('pais', 'Áustria', 5),
  ('pais', 'Áustria', 6),
  ('pais', 'Áustria', 7),
  ('pais', 'Áustria', 8),
  ('pais', 'Áustria', 9),
  ('pais', 'Áustria', 10),
  ('pais', 'Áustria', 11),
  ('pais', 'Áustria', 12),
  ('pais', 'Áustria', 13),
  ('pais', 'Áustria', 14),
  ('pais', 'Áustria', 15),
  ('pais', 'Áustria', 16),
  ('pais', 'Áustria', 17),
  ('pais', 'Áustria', 18),
  ('pais', 'Áustria', 19),
  ('pais', 'Áustria', 20),
  ('pais', 'Jordânia', 1),
  ('pais', 'Jordânia', 2),
  ('pais', 'Jordânia', 3),
  ('pais', 'Jordânia', 4),
  ('pais', 'Jordânia', 5),
  ('pais', 'Jordânia', 6),
  ('pais', 'Jordânia', 7),
  ('pais', 'Jordânia', 8),
  ('pais', 'Jordânia', 9),
  ('pais', 'Jordânia', 10),
  ('pais', 'Jordânia', 11),
  ('pais', 'Jordânia', 12),
  ('pais', 'Jordânia', 13),
  ('pais', 'Jordânia', 14),
  ('pais', 'Jordânia', 15),
  ('pais', 'Jordânia', 16),
  ('pais', 'Jordânia', 17),
  ('pais', 'Jordânia', 18),
  ('pais', 'Jordânia', 19),
  ('pais', 'Jordânia', 20),
  ('pais', 'Portugal', 1),
  ('pais', 'Portugal', 2),
  ('pais', 'Portugal', 3),
  ('pais', 'Portugal', 4),
  ('pais', 'Portugal', 5),
  ('pais', 'Portugal', 6),
  ('pais', 'Portugal', 7),
  ('pais', 'Portugal', 8),
  ('pais', 'Portugal', 9),
  ('pais', 'Portugal', 10),
  ('pais', 'Portugal', 11),
  ('pais', 'Portugal', 12),
  ('pais', 'Portugal', 13),
  ('pais', 'Portugal', 14),
  ('pais', 'Portugal', 15),
  ('pais', 'Portugal', 16),
  ('pais', 'Portugal', 17),
  ('pais', 'Portugal', 18),
  ('pais', 'Portugal', 19),
  ('pais', 'Portugal', 20),
  ('pais', 'Uzbequistão', 1),
  ('pais', 'Uzbequistão', 2),
  ('pais', 'Uzbequistão', 3),
  ('pais', 'Uzbequistão', 4),
  ('pais', 'Uzbequistão', 5),
  ('pais', 'Uzbequistão', 6),
  ('pais', 'Uzbequistão', 7),
  ('pais', 'Uzbequistão', 8),
  ('pais', 'Uzbequistão', 9),
  ('pais', 'Uzbequistão', 10),
  ('pais', 'Uzbequistão', 11),
  ('pais', 'Uzbequistão', 12),
  ('pais', 'Uzbequistão', 13),
  ('pais', 'Uzbequistão', 14),
  ('pais', 'Uzbequistão', 15),
  ('pais', 'Uzbequistão', 16),
  ('pais', 'Uzbequistão', 17),
  ('pais', 'Uzbequistão', 18),
  ('pais', 'Uzbequistão', 19),
  ('pais', 'Uzbequistão', 20),
  ('pais', 'Colômbia', 1),
  ('pais', 'Colômbia', 2),
  ('pais', 'Colômbia', 3),
  ('pais', 'Colômbia', 4),
  ('pais', 'Colômbia', 5),
  ('pais', 'Colômbia', 6),
  ('pais', 'Colômbia', 7),
  ('pais', 'Colômbia', 8),
  ('pais', 'Colômbia', 9),
  ('pais', 'Colômbia', 10),
  ('pais', 'Colômbia', 11),
  ('pais', 'Colômbia', 12),
  ('pais', 'Colômbia', 13),
  ('pais', 'Colômbia', 14),
  ('pais', 'Colômbia', 15),
  ('pais', 'Colômbia', 16),
  ('pais', 'Colômbia', 17),
  ('pais', 'Colômbia', 18),
  ('pais', 'Colômbia', 19),
  ('pais', 'Colômbia', 20),
  ('pais', 'Polônia', 1),
  ('pais', 'Polônia', 2),
  ('pais', 'Polônia', 3),
  ('pais', 'Polônia', 4),
  ('pais', 'Polônia', 5),
  ('pais', 'Polônia', 6),
  ('pais', 'Polônia', 7),
  ('pais', 'Polônia', 8),
  ('pais', 'Polônia', 9),
  ('pais', 'Polônia', 10),
  ('pais', 'Polônia', 11),
  ('pais', 'Polônia', 12),
  ('pais', 'Polônia', 13),
  ('pais', 'Polônia', 14),
  ('pais', 'Polônia', 15),
  ('pais', 'Polônia', 16),
  ('pais', 'Polônia', 17),
  ('pais', 'Polônia', 18),
  ('pais', 'Polônia', 19),
  ('pais', 'Polônia', 20),
  ('pais', 'Inglaterra', 1),
  ('pais', 'Inglaterra', 2),
  ('pais', 'Inglaterra', 3),
  ('pais', 'Inglaterra', 4),
  ('pais', 'Inglaterra', 5),
  ('pais', 'Inglaterra', 6),
  ('pais', 'Inglaterra', 7),
  ('pais', 'Inglaterra', 8),
  ('pais', 'Inglaterra', 9),
  ('pais', 'Inglaterra', 10),
  ('pais', 'Inglaterra', 11),
  ('pais', 'Inglaterra', 12),
  ('pais', 'Inglaterra', 13),
  ('pais', 'Inglaterra', 14),
  ('pais', 'Inglaterra', 15),
  ('pais', 'Inglaterra', 16),
  ('pais', 'Inglaterra', 17),
  ('pais', 'Inglaterra', 18),
  ('pais', 'Inglaterra', 19),
  ('pais', 'Inglaterra', 20),
  ('pais', 'Croácia', 1),
  ('pais', 'Croácia', 2),
  ('pais', 'Croácia', 3),
  ('pais', 'Croácia', 4),
  ('pais', 'Croácia', 5),
  ('pais', 'Croácia', 6),
  ('pais', 'Croácia', 7),
  ('pais', 'Croácia', 8),
  ('pais', 'Croácia', 9),
  ('pais', 'Croácia', 10),
  ('pais', 'Croácia', 11),
  ('pais', 'Croácia', 12),
  ('pais', 'Croácia', 13),
  ('pais', 'Croácia', 14),
  ('pais', 'Croácia', 15),
  ('pais', 'Croácia', 16),
  ('pais', 'Croácia', 17),
  ('pais', 'Croácia', 18),
  ('pais', 'Croácia', 19),
  ('pais', 'Croácia', 20),
  ('pais', 'Gana', 1),
  ('pais', 'Gana', 2),
  ('pais', 'Gana', 3),
  ('pais', 'Gana', 4),
  ('pais', 'Gana', 5),
  ('pais', 'Gana', 6),
  ('pais', 'Gana', 7),
  ('pais', 'Gana', 8),
  ('pais', 'Gana', 9),
  ('pais', 'Gana', 10),
  ('pais', 'Gana', 11),
  ('pais', 'Gana', 12),
  ('pais', 'Gana', 13),
  ('pais', 'Gana', 14),
  ('pais', 'Gana', 15),
  ('pais', 'Gana', 16),
  ('pais', 'Gana', 17),
  ('pais', 'Gana', 18),
  ('pais', 'Gana', 19),
  ('pais', 'Gana', 20),
  ('pais', 'Panamá', 1),
  ('pais', 'Panamá', 2),
  ('pais', 'Panamá', 3),
  ('pais', 'Panamá', 4),
  ('pais', 'Panamá', 5),
  ('pais', 'Panamá', 6),
  ('pais', 'Panamá', 7),
  ('pais', 'Panamá', 8),
  ('pais', 'Panamá', 9),
  ('pais', 'Panamá', 10),
  ('pais', 'Panamá', 11),
  ('pais', 'Panamá', 12),
  ('pais', 'Panamá', 13),
  ('pais', 'Panamá', 14),
  ('pais', 'Panamá', 15),
  ('pais', 'Panamá', 16),
  ('pais', 'Panamá', 17),
  ('pais', 'Panamá', 18),
  ('pais', 'Panamá', 19),
  ('pais', 'Panamá', 20),
  ('cocacola', 'Coca-Cola', 1),
  ('cocacola', 'Coca-Cola', 2),
  ('cocacola', 'Coca-Cola', 3),
  ('cocacola', 'Coca-Cola', 4),
  ('cocacola', 'Coca-Cola', 5),
  ('cocacola', 'Coca-Cola', 6),
  ('cocacola', 'Coca-Cola', 7),
  ('cocacola', 'Coca-Cola', 8),
  ('cocacola', 'Coca-Cola', 9),
  ('cocacola', 'Coca-Cola', 10),
  ('cocacola', 'Coca-Cola', 11),
  ('cocacola', 'Coca-Cola', 12),
  ('cocacola', 'Coca-Cola', 13),
  ('cocacola', 'Coca-Cola', 14)
on conflict (section, number) do update set
  section_type = excluded.section_type;
